// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Event struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	UserName     string    `json:"user_name"`
	DtReminder   time.Time `json:"dt_reminder"`
	BotMessageID int32     `json:"bot_message_id"`
	Message      string    `json:"message"`
	State        string    `json:"state"`
	DtCreated    time.Time `json:"dt_created"`
}
